IMPORTAÇÃO DAS BIBLIOTECAS

In [62]:
import pandas as pd

EXTRAÇÃO E LEITURA DAS BASES

In [63]:
url_base1 = "https://raw.githubusercontent.com/isidoropinheiro/Projeto-People-Analytics/main/Documentos/Base%20de%20Dados/base1_colaboradores.xlsx"

url_base2 = "https://raw.githubusercontent.com/isidoropinheiro/Projeto-People-Analytics/main/Documentos/Base%20de%20Dados/base2_desligamentos.xlsx"

df_colaboradores = pd.read_excel(url_base1)
df_desligamentos = pd.read_excel(url_base2)

VISUALIZAÇÃO DA BASE1 COLABORADORES

In [64]:
df_colaboradores.head(10)

,ID_Colaborador,Area,Cargo,Senioridade,Gestor,Regiao,Salario
0,COL00001,Jurídico,Gerente,Pleno,Gestor_022,BA,6296.45
1,COL00002,Produto,Assistente,Pleno,Gestor_007,BA,5618.52
2,COL00003,Operações,Desenvolvedor,Júnior,Gestor_001,SP,4394.38
3,COL00004,Dados,Coordenador,Júnior,Gestor_028,BA,3656.16
4,COL00005,Dados,Assistente,Pleno,Gestor_008,MG,6710.70
5,COL00006,Financeiro,Assistente,Pleno,Gestor_009,MG,4725.72
6,COL00007,Recursos Humanos,Desenvolvedor,Sênior,Gestor_025,SC,11582.96
7,COL00008,Produto,Gerente,Júnior,Gestor_015,RS,4317.93
8,COL00009,Financeiro,Gerente,Pleno,Gestor_030,MG,6740.92
9,COL00010,Marketing,Engenheiro de Dados,Pleno,Gestor_011,RJ,5140.31

ANALISANDO BASE1

O que procuramos:
1. Há problema de estrutura?
2. Há problema de qualidade?
3. Há enriquecimento que faça sentido?

ITENS INVESTIGADOS
- IDs duplicados;
- IDs vazios;
- valores vazios nas demais colunas;
- categorias inconsistentes, por exemplo "Júnior" × "Junior";
- espaços extras;
- diferenças de capitalização;
- salários como texto em vez de número;
- salários zerados ou negativos;
- valores salariais muito fora do padrão.

In [65]:
#Mostra informações gerais do DataFrame
df_colaboradores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Colaborador  500 non-null    object
 1   Area            500 non-null    object
 2   Cargo           500 non-null    object
 3   Senioridade     500 non-null    object
 4   Gestor          500 non-null    object
 5   Regiao          500 non-null    object
 6   Salario         500 non-null    float64
dtypes: float64(1), object(6)
memory usage: 27.5+ KB

In [66]:
# Verifica quantos valores ausentes existem em cada coluna
df_colaboradores.isnull().sum()

ID_Colaborador    0
Area              0
Cargo             0
Senioridade       0
Gestor            0
Regiao            0
Salario           0
dtype: int64

In [67]:
# Mostra quantos valores diferentes existem em cada coluna
df_colaboradores.nunique()

ID_Colaborador    500
Area                9
Cargo               8
Senioridade         5
Gestor             30
Regiao              8
Salario           500
dtype: int64

In [68]:
# Verifica IDs duplicados
df_colaboradores["ID_Colaborador"].duplicated().sum()

np.int64(0)

In [69]:
# Verifica IDs vazios
df_colaboradores["ID_Colaborador"].isnull().sum()

np.int64(0)

In [70]:
# Verifica strings vazias:
(df_colaboradores["ID_Colaborador"].astype(str).str.strip() == "").sum()

np.int64(0)

In [71]:
# Verifica valores vazios nas demais colunas
df_colaboradores.isnull().sum()

ID_Colaborador    0
Area              0
Cargo             0
Senioridade       0
Gestor            0
Regiao            0
Salario           0
dtype: int64

In [72]:
# Verifica valores preenchidos como texto vazio:
for coluna in df_colaboradores.columns:
    vazios = (
        df_colaboradores[coluna]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(f"{coluna}: {vazios} vazios")

ID_Colaborador: 0 vazios
Area: 0 vazios
Cargo: 0 vazios
Senioridade: 0 vazios
Gestor: 0 vazios
Regiao: 0 vazios
Salario: 0 vazios

In [73]:
# Verifica categorias existentes
print("Áreas:")
print(df_colaboradores["Area"].unique())

print("\nCargos:")
print(df_colaboradores["Cargo"].unique())

print("\nSenioridades:")
print(df_colaboradores["Senioridade"].unique())

print("\nGestores:")
print(df_colaboradores["Gestor"].unique())

print("\nRegiões:")
print(df_colaboradores["Regiao"].unique())

Áreas:
['Jurídico' 'Produto' 'Operações' 'Dados' 'Financeiro' 'Recursos Humanos'
 'Marketing' 'Tecnologia' 'Comercial']

Cargos:
['Gerente' 'Assistente' 'Desenvolvedor' 'Coordenador'
 'Engenheiro de Dados' 'Especialista' 'Analista' 'Consultor']

Senioridades:
['Pleno' 'Júnior' 'Sênior' 'Estágio' 'Especialista']

Gestores:
['Gestor_022' 'Gestor_007' 'Gestor_001' 'Gestor_028' 'Gestor_008'
 'Gestor_009' 'Gestor_025' 'Gestor_015' 'Gestor_030' 'Gestor_011'
 'Gestor_026' 'Gestor_010' 'Gestor_002' 'Gestor_024' 'Gestor_017'
 'Gestor_005' 'Gestor_020' 'Gestor_014' 'Gestor_004' 'Gestor_021'
 'Gestor_018' 'Gestor_019' 'Gestor_006' 'Gestor_013' 'Gestor_023'
 'Gestor_003' 'Gestor_027' 'Gestor_012' 'Gestor_029' 'Gestor_016']

Regiões:
['BA' 'SP' 'MG' 'SC' 'RS' 'RJ' 'DF' 'PR']

In [74]:
# Verifica espaços extras
for coluna in ["Area", "Cargo", "Senioridade", "Gestor", "Regiao"]:
    espacos = (
        df_colaboradores[coluna].astype(str)
        != df_colaboradores[coluna].astype(str).str.strip()
    ).sum()

    print(f"{coluna}: {espacos} registros com espaços extras")

Area: 0 registros com espaços extras
Cargo: 0 registros com espaços extras
Senioridade: 0 registros com espaços extras
Gestor: 0 registros com espaços extras
Regiao: 0 registros com espaços extras

In [75]:
# Verifica diferenças de capitalização
for coluna in ["Area", "Cargo", "Senioridade", "Gestor", "Regiao"]:
    original = df_colaboradores[coluna].nunique()
    padronizado = df_colaboradores[coluna].astype(str).str.lower().nunique()

    print(
        f"{coluna}: original = {original} | "
        f"ignorando maiúsculas/minúsculas = {padronizado}"
    )

Area: original = 9 | ignorando maiúsculas/minúsculas = 9
Cargo: original = 8 | ignorando maiúsculas/minúsculas = 8
Senioridade: original = 5 | ignorando maiúsculas/minúsculas = 5
Gestor: original = 30 | ignorando maiúsculas/minúsculas = 30
Regiao: original = 8 | ignorando maiúsculas/minúsculas = 8

In [76]:
# Verifica se salário é numérico
df_colaboradores["Salario"].dtype

dtype('float64')

In [77]:
# Confirma ou não se salário é numérico
pd.api.types.is_numeric_dtype(df_colaboradores["Salario"])

True

In [78]:
# Verifica salários zerados
(df_colaboradores["Salario"] == 0).sum()

np.int64(0)

In [79]:
# Verifica salários negativos
(df_colaboradores["Salario"] < 0).sum()

np.int64(0)

RESULTADOS DA VERIFICAÇÃO DA BASE1

Após as verificações realizadas na Base 1, foram identificados os seguintes resultados:

- IDs duplicados: **0**
- IDs nulos: **0**
- IDs vazios: **0**
- Valores nulos: **0**
- Strings vazias: **0**
- Salários zerados: **0**
- Salários negativos: **0**
- Salário armazenado como valor numérico: **Sim**

>Até o momento, não foram identificadas inconsistências que exijam tratamento nos campos analisados.

VISUALIZAÇÃO DA BASE2 DESLIGAMENTOS

In [80]:
df_desligamentos.head(10)

  ID_Colaborador Data_Admissao Data_Desligamento Motivo_Desligamento
0       COL00001    2024-09-12        2026-04-15  Pedido de demissão
1       COL00002    2021-08-08               NaT                 NaN
2       COL00003    2021-01-08               NaT                 NaN
3       COL00004    2021-06-15               NaT                 NaN
4       COL00005    2023-10-14               NaT                 NaN
5       COL00006    2025-01-04               NaT                 NaN
6       COL00007    2024-08-23               NaT                 NaN
7       COL00008    2025-09-26               NaT                 NaN
8       COL00009    2024-07-16        2027-07-30  Pedido de demissão
9       COL00010    2022-09-19               NaT                 NaN

ANALISANDO BASE 2

O que procuramos:
1. Há problema de estrutura?
2. Há problema de qualidade?
3. Há necessidade de tratamento ou enriquecimento?

ITENS INVESTIGADOS
- IDs duplicados;
- IDs vazios;
- valores vazios nas demais colunas;
- tipos das colunas;
- datas em formato adequado;
- datas de desligamento ausentes;
- datas de desligamento anteriores à admissão;
- datas de desligamento iguais à admissão;
- motivos de desligamento ausentes;
- motivos preenchidos de forma inconsistente.

In [81]:
# Mostra informações gerais do DataFrame
df_desligamentos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Colaborador       500 non-null    object
 1   Data_Admissao        500 non-null    datetime64[ns]
 2   Data_Desligamento    153 non-null    datetime64[ns]
 3   Motivo_Desligamento  158 non-null    object
dtypes: datetime64[ns](2), object(2)
memory usage: 15.8+ KB

In [82]:
# Verifica valores ausentes
df_desligamentos.isnull().sum()

ID_Colaborador           0
Data_Admissao            0
Data_Desligamento      347
Motivo_Desligamento    342
dtype: int64

In [83]:
# Mostra a quantidade de valores distintos
df_desligamentos.nunique()

ID_Colaborador         500
Data_Admissao          426
Data_Desligamento      150
Motivo_Desligamento      7
dtype: int64

In [84]:
# Verifica IDs duplicados
df_desligamentos["ID_Colaborador"].duplicated().sum()

np.int64(0)

In [85]:
# Verifica IDs nulos
df_desligamentos["ID_Colaborador"].isnull().sum()

np.int64(0)

In [86]:
# Verifica IDs preenchidos como string vazia
(
    df_desligamentos["ID_Colaborador"]
    .astype(str)
    .str.strip()
    .eq("")
    .sum()
)

np.int64(0)

In [87]:
# Verifica valores preenchidos como string vazia
for coluna in df_desligamentos.columns:
    vazios = (
        df_desligamentos[coluna]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(f"{coluna}: {vazios} vazios")

ID_Colaborador: 0 vazios
Data_Admissao: 0 vazios
Data_Desligamento: 0 vazios
Motivo_Desligamento: 0 vazios

In [88]:
# Verifica os valores existentes nos motivos de desligamento
df_desligamentos["Motivo_Desligamento"].unique()

array(['Pedido de demissão', nan, 'Outro', 'Desempenho', 'Reestruturação',
       'Fim de contrato', 'Salário', 'Mudança de carreira'], dtype=object)

In [89]:
# Verifica motivos preenchidos sem data de desligamento
(
    df_desligamentos["Motivo_Desligamento"].notnull()
    & df_desligamentos["Data_Desligamento"].isnull()
).sum()

np.int64(11)

In [90]:
# Verifica datas de desligamento sem motivo informado
(
    df_desligamentos["Data_Desligamento"].notnull()
    & df_desligamentos["Motivo_Desligamento"].isnull()
).sum()

np.int64(6)

In [91]:
# Verifica desligamentos anteriores à data de admissão
(
    df_desligamentos["Data_Desligamento"]
    < df_desligamentos["Data_Admissao"]
).sum()

np.int64(5)

In [92]:
# Verifica desligamentos na mesma data da admissão
(
    df_desligamentos["Data_Desligamento"]
    == df_desligamentos["Data_Admissao"]
).sum()

np.int64(5)

RESULTADOS DA VERIFICAÇÃO

Após as verificações realizadas na Base 2, foram identificados os seguintes resultados:

- IDs duplicados: **0**
- IDs nulos: **0**
- IDs vazios: **0**
- Strings vazias: **0**
- Data de admissão armazenada como data: **Sim**
- Data de desligamento armazenada como data: **Sim**
- Motivos de desligamento identificados: **6 categorias**
- Motivos preenchidos sem data de desligamento: **11**
- Datas de desligamento sem motivo informado: **6**
- Desligamentos anteriores à data de admissão: **5**
- Desligamentos na mesma data da admissão: **5**
<br>
CONCLUSÃO

A Base 2 apresenta estrutura adequada para utilização nas próximas etapas, porém foram identificadas algumas inconsistências de qualidade dos dados.

Os principais pontos identificados foram:

- registros com motivo de desligamento sem data correspondente;
- registros com data de desligamento sem motivo informado;
- registros com data de desligamento anterior à data de admissão;
- registros com admissão e desligamento na mesma data.

Os registros identificados serão avaliados antes de qualquer tratamento, considerando o impacto que cada situação pode gerar nos indicadores de People Analytics.

> Nem toda inconsistência identificada deve necessariamente ser corrigida. O tratamento deverá considerar o contexto do dado e seu impacto nas análises posteriores.
<br>


##CONSOLIDAÇÃO DAS BASES

- Com a análise das duas fontes concluída, será criada uma terceira base consolidada para utilização nas análises de People Analytics.

- A Base 3 será construída a partir da relação entre a Base 1 e a Base 2 por meio do campo `ID_Colaborador`.

- A consolidação permitirá reunir, em uma única estrutura, as informações cadastrais e organizacionais dos colaboradores e as informações relacionadas às suas admissões e desligamentos.
<br>
OBJETIVO DA BASE 3

- A Base 3 terá como objetivo disponibilizar uma visão consolidada dos colaboradores, servindo como principal fonte para as análises e indicadores das próximas etapas do projeto.

- A consolidação não terá como objetivo eliminar as inconsistências identificadas nas fontes originais.

- Os dados serão preservados e as situações identificadas durante a análise de qualidade serão sinalizadas por meio de campos auxiliares.
<br>

CAMPOS DERIVADOS

Além das informações provenientes das Bases 1 e 2, a Base 3 contará com campos derivados para facilitar as análises posteriores.

<br>
STATUS - O campo `Status` será utilizado para classificar o vínculo do colaborador. A regra inicial será:

- Data de desligamento preenchida → **Desligado**
- Data de desligamento não preenchida + motivo informado → **A validar**
- Data de desligamento não preenchida + motivo não informado → **Ativo**

>A classificação **A validar** permite identificar registros em que existe uma indicação de desligamento, mas não há uma data registrada para confirmar a situação.

<br>
FLAG DE QUALIDADE -
O campo `Flag_Qualidade` será utilizado para sinalizar inconsistências identificadas nos registros.

A flag permitirá preservar os dados originais e, ao mesmo tempo, identificar situações que possam exigir atenção durante as análises. Entre as situações identificadas estão:

- motivo de desligamento sem data;
- data de desligamento sem motivo;
- desligamento anterior à admissão;
- admissão e desligamento na mesma data.

<br>
TEMPO DE CASA - O campo `Tempo_de_Casa` será calculado a partir da diferença entre a data de admissão e a data de referência correspondente.

- Para colaboradores desligados, será considerada a data de desligamento.

- Para colaboradores ativos, será considerada a data atual.

>O resultado será apresentado em anos e meses, facilitando a interpretação dos dados nas análises de People Analytics.

<br>

##DECISÃO SOBRE O TRATAMENTO DOS DADOS

Neste momento, não serão realizadas correções automáticas ou exclusões dos registros identificados como inconsistentes. A decisão considera que uma inconsistência pode representar tanto um erro de preenchimento quanto uma situação que necessita de investigação. Dessa forma, a estratégia adotada será:

1. Preservar os dados originais;
2. Consolidar as informações das duas fontes;
3. Sinalizar as inconsistências encontradas;
4. Criar campos derivados que facilitem a análise;
5. Avaliar posteriormente o impacto dessas situações nos indicadores de People Analytics.

> O objetivo é evitar que o processo de tratamento elimine informações potencialmente relevantes antes que seu impacto analítico seja compreendido.

In [93]:
# CONSOLIDAÇÃO DAS BASES

df_base3 = pd.merge(
    df_colaboradores,
    df_desligamentos,
    on="ID_Colaborador",
    how="left"
)

df_base3.head(10)

,ID_Colaborador,Area,Cargo,Senioridade,Gestor,Regiao,Salario,Data_Admissao,Data_Desligamento,Motivo_Desligamento
0,COL00001,Jurídico,Gerente,Pleno,Gestor_022,BA,6296.45,2024-09-12,2026-04-15,Pedido de demissão
1,COL00002,Produto,Assistente,Pleno,Gestor_007,BA,5618.52,2021-08-08,NaT,NaN
2,COL00003,Operações,Desenvolvedor,Júnior,Gestor_001,SP,4394.38,2021-01-08,NaT,NaN
3,COL00004,Dados,Coordenador,Júnior,Gestor_028,BA,3656.16,2021-06-15,NaT,NaN
4,COL00005,Dados,Assistente,Pleno,Gestor_008,MG,6710.70,2023-10-14,NaT,NaN
5,COL00006,Financeiro,Assistente,Pleno,Gestor_009,MG,4725.72,2025-01-04,NaT,NaN
6,COL00007,Recursos Humanos,Desenvolvedor,Sênior,Gestor_025,SC,11582.96,2024-08-23,NaT,NaN
7,COL00008,Produto,Gerente,Júnior,Gestor_015,RS,4317.93,2025-09-26,NaT,NaN
8,COL00009,Financeiro,Gerente,Pleno,Gestor_030,MG,6740.92,2024-07-16,2027-07-30,Pedido de demissão
9,COL00010,Marketing,Engenheiro de Dados,Pleno,Gestor_011,RJ,5140.31,2022-09-19,NaT,NaN

In [94]:
# Verifica a estrutura da Base 3
df_base3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Colaborador       500 non-null    object
 1   Area                 500 non-null    object
 2   Cargo                500 non-null    object
 3   Senioridade          500 non-null    object
 4   Gestor               500 non-null    object
 5   Regiao               500 non-null    object
 6   Salario              500 non-null    float64
 7   Data_Admissao        500 non-null    datetime64[ns]
 8   Data_Desligamento    153 non-null    datetime64[ns]
 9   Motivo_Desligamento  158 non-null    object
dtypes: datetime64[ns](2), float64(1), object(7)
memory usage: 39.2+ KB

In [95]:
# Verifica a quantidade de registros e colunas
df_base3.shape

(500, 10)

In [96]:
# Cria o Status do colaborador
df_base3["Status"] = "Ativo"

df_base3.loc[
    df_base3["Data_Desligamento"].notnull(),
    "Status"
] = "Desligado"

df_base3.loc[
    df_base3["Data_Desligamento"].isnull()
    & df_base3["Motivo_Desligamento"].notnull(),
    "Status"
] = "A validar"

In [97]:
# Verifica a quantidade de colaboradores por Status
df_base3["Status"].value_counts()

Status
Ativo        336
Desligado    153
A validar     11
Name: count, dtype: int64

In [98]:
# Cria a coluna Flag_Qualidade
df_base3["Flag_Qualidade"] = "OK"

# Motivo informado sem data de desligamento
df_base3.loc[
    df_base3["Data_Desligamento"].isnull()
    & df_base3["Motivo_Desligamento"].notnull(),
    "Flag_Qualidade"
] = "Motivo sem data"

# Data de desligamento informada sem motivo
df_base3.loc[
    df_base3["Data_Desligamento"].notnull()
    & df_base3["Motivo_Desligamento"].isnull(),
    "Flag_Qualidade"
] = "Data sem motivo"

# Desligamento anterior à admissão
df_base3.loc[
    df_base3["Data_Desligamento"] < df_base3["Data_Admissao"],
    "Flag_Qualidade"
] = "Desligamento anterior à admissão"

# Admissão e desligamento na mesma data
df_base3.loc[
    df_base3["Data_Desligamento"] == df_base3["Data_Admissao"],
    "Flag_Qualidade"
] = "Admissão e desligamento na mesma data"

In [99]:
# Verifica a quantidade de registros por Flag_Qualidade
df_base3["Flag_Qualidade"].value_counts()

Flag_Qualidade
OK                                       474
Motivo sem data                           11
Desligamento anterior à admissão           5
Admissão e desligamento na mesma data      5
Data sem motivo                            5
Name: count, dtype: int64

VERIFICAÇÃO DAS INCONSISTÊNCIAS

Após a criação da `Flag_Qualidade`, foi realizada uma verificação específica dos registros que possuem data de desligamento, mas não possuem motivo informado.

>Essa verificação tem como objetivo identificar os registros envolvidos e avaliar se essas inconsistências também apresentam outras situações de qualidade, evitando que uma ocorrência seja sobrescrita por outra na criação da flag.

In [100]:
# Verifica registros com data de desligamento sem motivo
df_base3[
    df_base3["Data_Desligamento"].notnull()
    & df_base3["Motivo_Desligamento"].isnull()
][
    ["ID_Colaborador", "Data_Admissao", "Data_Desligamento", "Flag_Qualidade"]
]

,ID_Colaborador,Data_Admissao,Data_Desligamento,Flag_Qualidade
65,COL00066,2025-06-20,2025-06-20,Admissão e desligamento na mesma data
147,COL00148,2022-02-10,2025-06-15,Data sem motivo
181,COL00182,2025-01-01,2026-06-05,Data sem motivo
226,COL00227,2025-06-06,2028-05-22,Data sem motivo
370,COL00371,2023-05-08,2024-11-09,Data sem motivo
425,COL00426,2023-03-03,2026-04-05,Data sem motivo

ANÁLISE DA FLAG DE QUALIDADE

Durante a validação da `Flag_Qualidade`, foi identificado que algumas inconsistências podem ocorrer simultaneamente no mesmo registro.

- No conjunto analisado, um colaborador apresentou simultaneamente ausência de motivo de desligamento e admissão e desligamento na mesma data.

A lógica inicial da flag utilizava condições sequenciais, fazendo com que uma inconsistência pudesse sobrescrever outra. Dessa forma, a estrutura da flag será ajustada para permitir o registro de múltiplas inconsistências no mesmo colaborador.

> Uma mesma linha pode apresentar mais de um problema de qualidade. Portanto, a identificação das inconsistências não deve eliminar informações já encontradas durante a análise.

In [101]:
# Recria a Flag_Qualidade permitindo múltiplas inconsistências
df_base3["Flag_Qualidade"] = ""

# Motivo informado sem data de desligamento
df_base3.loc[
    df_base3["Data_Desligamento"].isnull()
    & df_base3["Motivo_Desligamento"].notnull(),
    "Flag_Qualidade"
] += "Motivo sem data; "

# Data de desligamento informada sem motivo
df_base3.loc[
    df_base3["Data_Desligamento"].notnull()
    & df_base3["Motivo_Desligamento"].isnull(),
    "Flag_Qualidade"
] += "Data sem motivo; "

# Desligamento anterior à admissão
df_base3.loc[
    df_base3["Data_Desligamento"] < df_base3["Data_Admissao"],
    "Flag_Qualidade"
] += "Desligamento anterior à admissão; "

# Admissão e desligamento na mesma data
df_base3.loc[
    df_base3["Data_Desligamento"] == df_base3["Data_Admissao"],
    "Flag_Qualidade"
] += "Admissão e desligamento na mesma data; "

# Registros sem inconsistências
df_base3.loc[
    df_base3["Flag_Qualidade"] == "",
    "Flag_Qualidade"
] = "OK"

# Remove o "; " do final das flags
df_base3["Flag_Qualidade"] = (
    df_base3["Flag_Qualidade"]
    .str.rstrip("; ")
)

CORREÇÃO DA FLAG DE QUALIDADE

Inicialmente, a coluna é criada vazia. As inconsistências são adicionadas à flag conforme cada condição é identificada.

- O uso de `+=` permite acumular mais de uma inconsistência no mesmo registro, evitando que uma nova condição sobrescreva uma inconsistência identificada anteriormente.

>Ao final, os registros que não apresentaram nenhuma inconsistência recebem a classificação `OK`.

In [104]:
# Verifica resultado
df_base3["Flag_Qualidade"].value_counts()

Flag_Qualidade
OK                                                        474
Motivo sem data                                            11
Desligamento anterior à admissão                            5
Data sem motivo                                             5
Admissão e desligamento na mesma data                       4
Data sem motivo; Admissão e desligamento na mesma data      1
Name: count, dtype: int64

In [105]:
# Cria a data de referência para o cálculo
data_referencia = pd.Timestamp.today()

# Calcula o tempo de casa em dias
df_base3["Tempo_de_Casa_Dias"] = (
    df_base3["Data_Desligamento"].fillna(data_referencia)
    - df_base3["Data_Admissao"]
).dt.days

In [106]:
# Verifica resultado
df_base3["Data_Desligamento"].fillna(data_referencia)

0     2026-04-15 00:00:00.000000
1     2026-10-05 21:33:39.165037
2     2026-10-05 21:33:39.165037
3     2026-10-05 21:33:39.165037
4     2026-10-05 21:33:39.165037
                 ...
495   2026-10-05 21:33:39.165037
496   2026-10-05 21:33:39.165037
497   2026-10-05 21:33:39.165037
498   2026-10-05 21:33:39.165037
499   2026-10-05 21:33:39.165037
Name: Data_Desligamento, Length: 500, dtype: datetime64[ns]

In [109]:
# Verifica o resultado do tempo de casa
df_base3["Tempo_de_Casa_Dias"].head(10)

0     580
1    1884
2    2096
3    1938
4    1087
5     639
6     773
7     374
8    1109
9    1477
Name: Tempo_de_Casa_Dias, dtype: int64

In [110]:
# Converte o tempo de casa para anos e meses
def calcular_tempo_de_casa(dias):
    anos = dias // 365
    meses = (dias % 365) // 30

    if anos > 0 and meses > 0:
        return f"{anos} anos, {meses} meses"
    elif anos > 0:
        return f"{anos} anos"
    else:
        return f"{meses} meses"

df_base3["Tempo_de_Casa"] = (
    df_base3["Tempo_de_Casa_Dias"]
    .apply(calcular_tempo_de_casa)
)

In [111]:
# Verifica o tempo de casa calculado
df_base3[
    [
        "ID_Colaborador",
        "Data_Admissao",
        "Data_Desligamento",
        "Status",
        "Tempo_de_Casa"
    ]
].head(10)

  ID_Colaborador Data_Admissao Data_Desligamento     Status     Tempo_de_Casa
0       COL00001    2024-09-12        2026-04-15  Desligado   1 anos, 7 meses
1       COL00002    2021-08-08               NaT      Ativo   5 anos, 1 meses
2       COL00003    2021-01-08               NaT      Ativo   5 anos, 9 meses
3       COL00004    2021-06-15               NaT      Ativo   5 anos, 3 meses
4       COL00005    2023-10-14               NaT      Ativo  2 anos, 11 meses
5       COL00006    2025-01-04               NaT      Ativo   1 anos, 9 meses
6       COL00007    2024-08-23               NaT      Ativo   2 anos, 1 meses
7       COL00008    2025-09-26               NaT      Ativo            1 anos
8       COL00009    2024-07-16        2027-07-30  Desligado            3 anos
9       COL00010    2022-09-19               NaT      Ativo            4 anos

In [112]:
# Corrige a apresentação de anos e meses
def calcular_tempo_de_casa(dias):
    anos = dias // 365
    meses = (dias % 365) // 30

    partes = []

    if anos > 0:
        partes.append(f"{anos} ano" if anos == 1 else f"{anos} anos")

    if meses > 0:
        partes.append(f"{meses} mês" if meses == 1 else f"{meses} meses")

    return ", ".join(partes)

df_base3["Tempo_de_Casa"] = (
    df_base3["Tempo_de_Casa_Dias"]
    .apply(calcular_tempo_de_casa)
)

In [113]:
# Verifica o resultado final do tempo de casa
print(df_base3["Tempo_de_Casa"].head(10))

0      1 ano, 7 meses
1       5 anos, 1 mês
2     5 anos, 9 meses
3     5 anos, 3 meses
4    2 anos, 11 meses
5      1 ano, 9 meses
6       2 anos, 1 mês
7               1 ano
8              3 anos
9              4 anos
Name: Tempo_de_Casa, dtype: object

In [114]:
# Remove a coluna auxiliar utilizada no cálculo
df_base3.drop(
    columns=["Tempo_de_Casa_Dias"],
    inplace=True
)

In [115]:
# Verifica a estrutura final da Base 3
df_base3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Colaborador       500 non-null    object
 1   Area                 500 non-null    object
 2   Cargo                500 non-null    object
 3   Senioridade          500 non-null    object
 4   Gestor               500 non-null    object
 5   Regiao               500 non-null    object
 6   Salario              500 non-null    float64
 7   Data_Admissao        500 non-null    datetime64[ns]
 8   Data_Desligamento    153 non-null    datetime64[ns]
 9   Motivo_Desligamento  158 non-null    object
 10  Status               500 non-null    object
 11  Flag_Qualidade       500 non-null    object
 12  Tempo_de_Casa        500 non-null    object
dtypes: datetime64[ns](2), float64(1), object(10)
memory usage: 50.9+ KB

In [116]:
# Exporta a Base 3 para Excel
nome_arquivo = "base3_dados_consolidados.xlsx"

df_base3.to_excel(
    nome_arquivo,
    index=False,
    sheet_name="Dados Consolidados"
)

print(f"Base criada com sucesso: {nome_arquivo}")

Base criada com sucesso: base3_dados_consolidados.xlsx

CONSIDERAÇÕES FINAIS

A análise e consolidação das Bases 1 e 2 permitiu estruturar uma Base 3 com informações cadastrais, organizacionais e de desligamento dos colaboradores.

Durante o processo, foram identificadas inconsistências nos dados de desligamento. Essas situações foram preservadas e sinalizadas por meio da `Flag_Qualidade`, evitando alterações nos dados originais antes da avaliação de seu impacto analítico.

Também foram criados campos derivados para apoiar as próximas análises:

- `Status`;
- `Flag_Qualidade`;
- `Tempo_de_Casa`.

A Base 3 está estruturada para servir como fonte das próximas etapas do projeto, nas quais serão desenvolvidos indicadores de People Analytics e avaliados os impactos das inconsistências identificadas.

>Como evolução futura, as regras de tratamento poderão ser refinadas de acordo com o indicador analisado e com a necessidade de negócio.